UPDATE
	[DS_TRAINNING].[dbo].[WRK_PRODUTOS_ESTOQUE]
SET
	[DESC_PROUTO] = 'VALOR QUALQUER'
  , [DESC_ABV] = 'OUTRO VALOR'
WHERE
	[CODIGO] = 100 AND [FIM_VIGENCIA] IS NULL
GO


UPDATE
	[DS_TRAINNING].[dbo].[WRK_PRODUTOS_ESTOQUE]
SET
	[FIM_VIGENCIA] = ?
WHERE
	[CODIGO] = ? AND [FIM_VIGENCIA] IS NULL
GO