SELECT
	[SK_PRODUTO]
  , [CODIGO]
  , [DESC_PROUTO]
  , [DESC_ABV]
  , [Unidades]
  , [FIM_VIGENCIA]
  , [INI_VIGENCIA]
FROM
	[DS_TRAINNING].[dbo].[WRK_PRODUTOS_ESTOQUE]
WHERE
	[FIM_VIGENCIA] IS NULL
GO